language: node_js
os:
  - osx
  - linux
node_js: 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      set -e
      /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
      disown -ar
      echo "Started xvfb"
    fi

env:
  global:
    - DISPLAY=:10

install:
  - yarn
  - cd server && yarn
  - cd ..

script:
  - yarn test

after_success:
  - cd server && yarn coverage && cd ..

cache: yarn
